### PR TITLE
- Fix typo in comment

### PR DESCRIPTION
**Pull request by rjschwei**
### Summary

Fix typo in a comment

### Testing

N/A

New tests cover the changes: 

N/A

### Description for the changelog

Fix typo in comment

### Licensing

This contribution is under the terms of the Apache 2.0 License:  yes

### CODE REVIEW

**Comment by yunhee-l** [comment]
Please rebase this PR against aws:dev branch.

**Comment by sparrc** [comment]
closing for inactivity

**Comment by rjschwei** [comment]
Sorry this slipped through the cracks. Rebased.

**Comment by rjschwei** [comment]
@sparrc Can you re-open to merge or do I need a new PR?

Thanks

**Comment by sparrc** [comment]
looks like I can't reopen, if you open a new PR i will get it merged asap

**Pull request closed without merging**
