### PR TITLE
Added command line to show verison info of ecs-init

### PR DESCRIPTION
**Pull request by richardpen**
Added the command to show ecs-init hash in running command: `/usr/libexec/amazon-ecs-init version` Sample output:

```
$ /usr/libexec/amazon-ecs-init version
ecs-init version 1.12.2 (4433607)
```

### CODE REVIEW

**Comment by aaithal** [comment]
:shipit:

**Comment by samuelkarp** [comment]
:+1:

**Comment by samuelkarp** [comment]
[Merged](https://github.com/aws/amazon-ecs-init/commit/c31c6d0de9eba606805294a8ba928d53cc158eaf).

**Pull request closed without merging**
