### PR TITLE
Add systemd support for debian based distros

### PR DESCRIPTION
**Pull request by kshcherban**
### Summary
Added systemd service and packaging wrappers for debian based package. 

### Testing
Tested on one instance in my internal ECS cluster.

New tests cover the changes: no
There're no tests for packaging.

### Licensing
This contribution is under the terms of the Apache 2.0 License: yes

### CODE REVIEW

**Comment by brainstorm** [comment]
Yes @kshcherban! Please someone from AWS merge this! ;)

**Comment by kshcherban** [comment]
I didn't find a way to manage ecs-agent startup parameters with this software. In case you want to enable awsvpc task networking please add following parameters to ecs-agent docker container run command:
```
--init
--env=ECS_ENABLE_TASK_ENI=true
--volume=/sbin:/sbin
--volume=/lib:/lib
--volume=/lib64:/lib64
--volume=/usr/lib:/usr/lib
--volume=/proc:/host/proc
--volume=/sys/fs/cgroup:/sys/fs/cgroup
--volume=/var/lib/ecs/dhclient:/var/lib/dhclient
--cap-add=sys_admin
--cap-add=net_admin
```

**Comment by brainstorm** [comment]
Yeah, I encountered similar issues, I went for `--privileged` instead: https://github.com/johanmeiring/ansible-ubuntu-ecs-agent/pull/2

**Comment by nmeyerhans** [comment]
Please also see #109, which introduces a unit file to run the ECS agent directly from systemd instead of using ecs-init. It does not implement the instance component of the [UpdateContainerAgent](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_UpdateContainerAgent.html) API, but if you can live without that, then running directly from systemd eliminates the overhead of the additional ecs-init process.

I haven't integrated the unit file into the .deb packaging, since it largely eliminates the need for the .deb. I simply pull the unit file directly from github via a userdata script, e.g. 

```
curl -L -o /etc/systemd/system/ecs.service \
     https://raw.githubusercontent.com/nmeyerhans/amazon-ecs-init/${unit_file_commitid}/integration/systemd/ecs-agent.service

# Use the specified agent:
mkdir /etc/systemd/system/ecs.service.d/
cat <<EOF > /etc/systemd/system/ecs.service.d/version.conf
[Service]
Environment=ECS_AGENT_VERSION=v1.20.0
EOF

systemctl daemon-reload
systemctl start ecs.service
```

YMMV

**Comment by brainstorm** [comment]
Yeah, thanks @nmeyerhans, I ended up going the systemd+docker way:

https://github.com/umccr/umccrise/blob/master/deploy/roles/brainstorm.ecs-agent/tasks/main.yml#L55

Since the container by itself did not respond well to updates to CLUSTER_NAME and SIGHUPs, unfortunately.

**Comment by sparrc** [comment]
closing in favor of https://github.com/aws/amazon-ecs-init/pull/347

**Pull request closed without merging**
