### PR TITLE
 Update to support Agent 1.12.0

### PR DESCRIPTION
**Pull request by aaithal**
* Enable Task IAM Role for containers launched with 'host' network mode
* Change log for 1.12.0

r? @samuelkarp @richardpen @juanrhenals

### CODE REVIEW

**Comment by richardpen** [comment]
You also need to change the s3 bucket url like [this]( https://github.com/aws/amazon-ecs-init/commit/8d44eedc208ae3f8445992b2ce598d24f4344330)

**Comment by aaithal** [comment]
Ah, missed that. Updated now. Thanks!

**Comment by richardpen** [comment]
👍

**Comment by samuelkarp** [comment]
:+1:

**Comment by juanrhenals** [comment]
👍

**Pull request closed without merging**
