### PR TITLE
Update to support Agent 1.2.0 with Telemetry

### PR DESCRIPTION
**Pull request by samuelkarp**
I have not actually tested this yet but wanted to get the change out for review earlier rather than later.

r? @euank @aaithal

### CODE REVIEW

**Comment by aaithal** [comment]
Looks good. I can test if execdriver mount breaks any of the current assumptions.

**Comment by samuelkarp** [comment]
Thanks!  Let me know what works for you.  I'll also do my own testing today.

**Comment by euank** [comment]
LGTM assuming the above mentioned testing doesn't uncover anything.

**Comment by aaithal** [comment]
Tested that config changes work for docker 1.6.2. :ship:

**Pull request merged**
